package com.model;

import java.util.List;
/**
 * TWenjuan generated by MyEclipse Persistence Tools
 */

public class TWenjuan implements java.io.Serializable
{

	private String id;
	private String mingcheng;
	private String shijian;
	
	private List toupiaoList;
	
	public String getId()
	{
		return id;
	}
	public void setId(String id)
	{
		this.id = id;
	}
	public String getMingcheng()
	{
		return mingcheng;
	}
	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public List getToupiaoList()
	{
		return toupiaoList;
	}
	public void setToupiaoList(List toupiaoList)
	{
		this.toupiaoList = toupiaoList;
	}
	
}