package com.model;

/**
 * TToupiaoxuanxiang generated by MyEclipse Persistence Tools
 */
public class TToupiaoxuanxiang implements java.io.Serializable
{

	private String id;
	private String xuanxiangneirong;
	private Integer piaoshu;
	private String toupiao_id;
	
	
	public String getId()
	{
		return id;
	}
	public void setId(String id)
	{
		this.id = id;
	}
	public Integer getPiaoshu()
	{
		return piaoshu;
	}
	public void setPiaoshu(Integer piaoshu)
	{
		this.piaoshu = piaoshu;
	}
	
	public String getToupiao_id()
	{
		return toupiao_id;
	}
	public void setToupiao_id(String toupiao_id)
	{
		this.toupiao_id = toupiao_id;
	}
	public String getXuanxiangneirong()
	{
		return xuanxiangneirong;
	}
	public void setXuanxiangneirong(String xuanxiangneirong)
	{
		this.xuanxiangneirong = xuanxiangneirong;
	}

}